name: flatter
description: We make Flutter flat, We are Flatter.
version: 0.1.0
homepage: https://github.com/Open-Bytes/Flatter.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
